services:
  db-migrate-remote:
    image: flyway/flyway:10-alpine
    env_file: .env        
    environment:
      FLYWAY_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./db/migrations:/flyway/sql:ro
   
