services:
  db:
    image: mysql:8.4
    container_name: shared-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: payments
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecretSTRONG!
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
