name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8
        env:
            MYSQL_DATABASE: payment_service
            MYSQL_ROOT_PASSWORD: 18sep2000*
        ports:
            - 3307:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build payment-system
        working-directory: payment-system
        run: mvn clean install